name: fsa-program-explorer
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile.web
    github:
      repo: YOUR_GITHUB_USERNAME/farmScraper
      branch: main
      deploy_on_push: true
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
